app <- ShinyDriver$new("../")
app$snapshotInit("mytest")

app$setInputs(package = "")
app$setInputs(package = "sf")
app$setInputs(`package-selectized` = "sf")
app$snapshot()
app$setInputs(distros = "Xenial")
app$snapshot()
app$setInputs(rvers = "3.5")
app$snapshot()
app$setInputs(distros = c("Xenial", "OpenSUSE 15"))
app$setInputs(distros = c("Xenial", "OpenSUSE 15", "OpenSUSE 42"))
app$setInputs(rvers = c("3.5", "3.6"))
app$snapshot()
